/**
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 *
 * Generated by: scripts/generate-cms-snapshot.mjs
 * Generated at: 2026-05-30T07:12:29.170Z
 * Site ID: d2744793-43f5-4587-a441-3ee0fa38f864
 * Matched docs: 21
 */

import type { Locale } from "./i18n";
import type {
  CabinContent,
  ContactFormSectionContent,
  LocalizedContent,
  PracticalContent,
  SiteConfig,
} from "./content";

type LocalizedMap<T> = Partial<Record<Locale, T>>;

export type GeneratedContentSnapshot = {
  siteConfig: LocalizedMap<Partial<SiteConfig>>;
  cabin: LocalizedMap<CabinContent>;
  home: LocalizedMap<Partial<LocalizedContent>>;
  practical: LocalizedMap<PracticalContent>;
  area: LocalizedMap<LocalizedContent["area"]>;
  privacy: LocalizedMap<LocalizedContent["privacy"]>;
  contactForm: LocalizedMap<ContactFormSectionContent>;
};

export const generatedContentSnapshot: GeneratedContentSnapshot = {
  "siteConfig": {
    "en": {
      "name": "Fageråsen 701",
      "bedrooms": 3,
      "capacity": 8,
      "location": "Fageråsen, Trysil, Norway",
      "bathrooms": 2,
      "mapLinkUrl": "https://www.openstreetmap.org/?mlat=61.332251&mlon=12.165275#map=16/61.332251/12.165275",
      "mapEmbedUrl": "https://www.openstreetmap.org/export/embed.html?bbox=12.155%2C61.322%2C12.175%2C61.342&layer=mapnik&marker=61.332251%2C12.165275"
    },
    "nl": {
      "name": "Fageråsen 701",
      "bedrooms": 3,
      "capacity": 8,
      "location": "Fageråsen, Trysil, Noorwegen",
      "bathrooms": 2,
      "mapLinkUrl": "https://www.openstreetmap.org/?mlat=61.332251&mlon=12.165275#map=16/61.332251/12.165275",
      "mapEmbedUrl": "https://www.openstreetmap.org/export/embed.html?bbox=12.155%2C61.322%2C12.175%2C61.342&layer=mapnik&marker=61.332251%2C12.165275"
    },
    "no": {
      "name": "Fageråsen 701",
      "bedrooms": 3,
      "capacity": 8,
      "location": "Fageråsen, Trysil, Norge",
      "bathrooms": 2,
      "mapLinkUrl": "https://www.openstreetmap.org/?mlat=61.332251&mlon=12.165275#map=16/61.332251/12.165275",
      "mapEmbedUrl": "https://www.openstreetmap.org/export/embed.html?bbox=12.155%2C61.322%2C12.175%2C61.342&layer=mapnik&marker=61.332251%2C12.165275"
    }
  },
  "cabin": {
    "en": {
      "hero": {
        "title": "Cosy ski-in/out mountain cabin with sauna",
        "badges": [
          {
            "label": "Sleeps",
            "value": "8–9"
          },
          {
            "label": "Altitude",
            "value": "800 m"
          },
          {
            "label": "Sauna",
            "value": "Private"
          }
        ],
        "subtitle": "Detached chalet in Fageråsen (Trysil) with ski-in/ski-out access, private sauna, and panoramic mountain views."
      },
      "meta": {
        "name": "Cosy ski-in/out mountain cabin with sauna",
        "sleeps": "8–9",
        "altitude": "800 m",
        "locationShort": "Fageråsen, Trysil, Norway"
      },
      "location": {
        "title": "Location",
        "mapQuery": "Fageråsen 701, Trysil",
        "distances": [
          {
            "label": "Transport track",
            "value": "approx. 50 m"
          },
          {
            "label": "Cross-country ski trail",
            "value": "approx. 150 m"
          },
          {
            "label": "Ski lift (Skistar Høyfjellssenter)",
            "value": "approx. 1.4 km"
          },
          {
            "label": "Skistar Lodge with restaurants, spa, shops and bar",
            "value": "7 minutes walk or skiing distance"
          },
          {
            "label": "Hiking and mountain bike trails",
            "value": "nearby"
          }
        ]
      },
      "policies": {
        "title": "Policies",
        "blocks": [
          {
            "items": [
              "50% of the total amount is due at time of reservation.",
              "The remaining amount is to be paid 7 day(s) before arrival."
            ],
            "title": "Payment schedule"
          },
          {
            "items": [
              "All paid prepayments are non-refundable."
            ],
            "title": "Cancellation policy"
          },
          {
            "items": [
              "No security deposit is due."
            ],
            "title": "Security deposit"
          }
        ]
      },
      "amenities": {
        "title": "Amenities",
        "groups": [
          {
            "items": [
              "Private dry sauna"
            ],
            "title": "Pool & spa"
          },
          {
            "items": [
              "Parking included",
              "EV charger at the chalet",
              "Private garden",
              "Private playground",
              "Private porch"
            ],
            "title": "Parking & facilities"
          },
          {
            "items": [
              "Children welcome",
              "Low allergen environment",
              "Smoking not allowed"
            ],
            "title": "Policies"
          },
          {
            "items": [
              "BBQ charcoal grill",
              "BBQ gas",
              "Blender",
              "Children's high chair",
              "Coffee machine",
              "Cooking utensils",
              "Dishwasher",
              "Grill",
              "Kitchen stove",
              "Microwave",
              "Oven",
              "Refrigerator",
              "Toaster",
              "Vacuum cleaner"
            ],
            "title": "Kitchen & dining"
          },
          {
            "items": [
              "Mountain",
              "Resort",
              "Ski in/out"
            ],
            "title": "Location features"
          },
          {
            "items": [
              "Clothes dryer",
              "Essentials",
              "Iron & board",
              "Shower",
              "Washbasin",
              "Washing machine"
            ],
            "title": "Bathroom & laundry"
          },
          {
            "items": [
              "Air conditioning",
              "Electric heating",
              "Fireplace",
              "Floor heating",
              "Heating available",
              "Wood/tiled stove"
            ],
            "title": "Heating & cooling"
          },
          {
            "items": [
              "Stereo system",
              "TV (antenna)"
            ],
            "title": "Entertainment"
          },
          {
            "items": [
              "Wireless broadband internet"
            ],
            "title": "Internet & office"
          },
          {
            "items": [
              "Fire extinguisher",
              "First aid kit",
              "Smoke detector"
            ],
            "title": "Home safety"
          }
        ]
      },
      "experience": [
        "Ski in/out",
        "Private sauna",
        "Panoramic views",
        "Trails at the house",
        "Family friendly loft"
      ],
      "houseRules": {
        "title": "House rules",
        "bullets": [
          "Children welcome",
          "Low allergen environment",
          "Smoking not allowed"
        ],
        "checkIn": "From 17:00",
        "checkOut": "By 10:00",
        "wifiNote": "Free Wi-Fi is available throughout the chalet.",
        "checkInNote": "Check-in via electronic lock with personal code.",
        "cleaningNote": "Linen rental and final cleaning of bathrooms and living areas are mandatory and charged separately. Guests are asked to leave the chalet tidy: remove trash and ashes from the fireplace, put all furniture back in place (inside and outside), and leave used dishes, cookware, oven, and microwave clean."
      },
      "description": [
        "Detached chalet in Fageråsen (Trysil) with ski-in/ski-out access, private sauna, and panoramic mountain views. Sleeps 8–9. Covered veranda with BBQ and heater. Cozy living room with wood-burning stove, 2 bathrooms, child-friendly loft, and fully equipped kitchen. Hiking and mountain bike trails start at the house. Quiet location at 800 m altitude, a 7-minute walk from Skistar Lodge. Perfect for comfort, nature, and active holidays in any season.",
        "The house is very suitable for families and groups. The chalet comfortably sleeps 8 people, with an extra-wide bed (120 cm) in the loft. Due to the sloped roof, this bed is particularly suitable for two children or one adult."
      ],
      "accessAndTransport": {
        "car": [
          "Car access from Oslo via E6/Rv3/Rv25 towards Trysil."
        ],
        "notes": [
          "Please note that the road to the chalet is a toll road."
        ],
        "title": "Access & transport",
        "parking": [
          "Ample parking directly at the chalet",
          "Shuttle bus passes every 30 minutes in the morning and afternoon",
          "Charging: EV charger at the chalet."
        ],
        "airports": [
          "Scandinavian Mountains Airport (Sälen/Trysil): 40 minutes",
          "Oslo Airport Gardermoen: 2.5 hours"
        ],
        "publicTransport": [
          "Nor-Way Trysil Express to Skistar Lodge: approx. 3 hours",
          "From Oslo S: Trysil Express train in 3.5 hours",
          "Fjällexpressen from Malmö, Gothenburg and Stockholm during winter season"
        ]
      },
      "layoutAndFacilities": {
        "items": [
          "4 bedrooms with 5 beds",
          "2 bedrooms with double beds (150 x 200 cm)",
          "1 bedroom with bunk bed (75 × 185 cm) – suitable for children or young adults",
          "Attic room with single bed (90 x 200 cm) + extra-wide bed (120 x 200 cm), suitable for 1 adult or 2 children",
          "Child-friendly play corner in the attic with daybed (120 x 175 cm), TV and stair gate",
          "2 bathrooms with shower and toilet, one with direct access to the sauna",
          "Cozy living room with wood-burning stove, TV and mountain views",
          "Fully equipped kitchen with hob, oven, microwave, dishwasher, refrigerator, freezer, Nespresso machine with milk frother and kettle",
          "Laundry room with washing machine, dryer and separate indoor storage for luggage and sports equipment"
        ],
        "title": "Layout & facilities"
      }
    },
    "nl": {
      "hero": {
        "title": "Sfeervol ski-in/out bergchalet met panoramisch uitzicht en sauna",
        "badges": [
          {
            "label": "Slaapplaatsen",
            "value": "8–9"
          },
          {
            "label": "Hoogte",
            "value": "800 m"
          },
          {
            "label": "Sauna",
            "value": "Privé"
          }
        ],
        "subtitle": "Vrijstaand chalet in Fageråsen (Trysil) met ski-in/ski-out, privé sauna en panoramisch bergzicht."
      },
      "meta": {
        "name": "Sfeervol ski-in/out bergchalet met panoramisch uitzicht en sauna",
        "sleeps": "8–9",
        "altitude": "800 m",
        "locationShort": "Fageråsen, Trysil, Noorwegen"
      },
      "location": {
        "title": "Locatie",
        "mapQuery": "Fageråsen 701, Trysil",
        "distances": [
          {
            "label": "Transporttrack",
            "value": "ca. 50 m"
          },
          {
            "label": "Langlaufloipe",
            "value": "ca. 150 m"
          },
          {
            "label": "Skilift (Skistar Høyfjellssenter)",
            "value": "ca. 1,4 km"
          },
          {
            "label": "Skistar Lodge met restaurants, spa, winkels en bar",
            "value": "7 minuten lopen of ski-afstand"
          }
        ]
      },
      "policies": {
        "title": "Voorwaarden",
        "blocks": [
          {
            "items": [
              "50% van het totaalbedrag is verschuldigd bij reservering.",
              "Het resterende bedrag dient 7 dag(en) voor aankomst te worden betaald."
            ],
            "title": "Betalingsschema"
          },
          {
            "items": [
              "Alle betaalde vooruitbetalingen zijn niet restitueerbaar."
            ],
            "title": "Annuleringsbeleid"
          },
          {
            "items": [
              "Er is geen borg verschuldigd."
            ],
            "title": "Borg"
          }
        ]
      },
      "amenities": {
        "title": "Voorzieningen",
        "groups": [
          {
            "items": [
              "Privé droge sauna"
            ],
            "title": "Wellness & spa"
          },
          {
            "items": [
              "Parkeren inbegrepen",
              "Laadpunt bij het chalet",
              "Privétuin",
              "Privé speelplaats",
              "Privé veranda"
            ],
            "title": "Parkeren & faciliteiten"
          },
          {
            "items": [
              "Kinderen welkom",
              "Allergiearme omgeving",
              "Roken niet toegestaan"
            ],
            "title": "Regels"
          },
          {
            "items": [
              "Houtskool BBQ",
              "Gas BBQ",
              "Blender",
              "Kinderstoel",
              "Koffiemachine",
              "Kookgerei",
              "Vaatwasser",
              "Grill",
              "Kookplaat",
              "Magnetron",
              "Oven",
              "Koelkast",
              "Broodrooster",
              "Stofzuiger"
            ],
            "title": "Keuken & eetruimte"
          },
          {
            "items": [
              "Berg",
              "Resort",
              "Ski in/out"
            ],
            "title": "Locatiekenmerken"
          },
          {
            "items": [
              "Wasdroger",
              "Basisbenodigdheden",
              "Strijkijzer & plank",
              "Douche",
              "Wastafel",
              "Wasmachine"
            ],
            "title": "Badkamer & wasruimte"
          },
          {
            "items": [
              "Airconditioning",
              "Elektrische verwarming",
              "Open haard",
              "Vloerverwarming",
              "Verwarming beschikbaar",
              "Hout-/tegelkachel"
            ],
            "title": "Verwarming & koeling"
          },
          {
            "items": [
              "Stereo-installatie",
              "TV (antenne)"
            ],
            "title": "Entertainment"
          },
          {
            "items": [
              "Draadloos breedbandinternet"
            ],
            "title": "Internet & werkplek"
          },
          {
            "items": [
              "Brandblusser",
              "EHBO-kit",
              "Rookmelder"
            ],
            "title": "Veiligheid"
          }
        ]
      },
      "experience": [
        "Ski in/out",
        "Privé sauna",
        "Panoramisch uitzicht",
        "Routes starten bij het huis",
        "Kindvriendelijke vide"
      ],
      "houseRules": {
        "title": "Goed om te weten",
        "bullets": [
          "Kinderen welkom",
          "Allergiearme omgeving",
          "Roken niet toegestaan"
        ],
        "checkIn": "Vanaf 17:00",
        "checkOut": "Voor 10:00",
        "wifiNote": "Gratis wifi is beschikbaar in het hele chalet.",
        "checkInNote": "Inchecken via elektronisch slot met persoonlijke code.",
        "cleaningNote": "Linnenverhuur en eindschoonmaak van badkamers en woonruimtes zijn verplicht en worden apart in rekening gebracht. Gasten wordt gevraagd het chalet netjes achter te laten: afval en as uit de open haard verwijderen, alle meubels terugplaatsen (binnen en buiten) en gebruikte borden, pannen, oven en magnetron schoon achterlaten."
      },
      "description": [
        "Vrijstaand chalet in Fageråsen (Trysil) met ski-in/ski-out, privé sauna en panoramisch bergzicht. Overdekte veranda met BBQ en heater. Gezellige woonkamer met houtkachel, 2 badkamers, kindvriendelijke vide en volledig uitgeruste keuken. Wandel- en mountainbikeroutes starten bij het huis. Rustige ligging op 800 m hoogte, 7 minuten lopen van Skistar Lodge. Perfect voor comfort, natuur en actieve vakanties in elk seizoen.",
        "Het huis is zeer geschikt voor gezinnen en groepen. Het chalet biedt comfortabel plaats aan 8-9 personen."
      ],
      "accessAndTransport": {
        "car": [
          "Met de auto vanuit Oslo via E6/Rv3/Rv25 richting Trysil."
        ],
        "notes": [
          "Let op: de weg naar het chalet is een tolweg."
        ],
        "title": "Bereikbaarheid & vervoer",
        "parking": [
          "Ruime parkeergelegenheid direct bij het chalet",
          "Shuttlebus rijdt elke 30 minuten in de ochtend en middag",
          "Opladen: laadpunt bij het chalet."
        ],
        "airports": [
          "Scandinavian Mountains Airport (Sälen/Trysil): 40 minuten",
          "Oslo Airport Gardermoen: 2,5 uur"
        ],
        "publicTransport": [
          "Nor-Way Trysil Express naar Skistar Lodge: ca. 3 uur",
          "Vanaf Oslo S: Trysil Express trein in 3,5 uur",
          "Fjällexpressen vanuit Malmö, Göteborg en Stockholm in het winterseizoen"
        ]
      },
      "layoutAndFacilities": {
        "items": [
          "4 slaapkamers, met 5 bedden",
          "2 slaapkamers met tweepersoonsbedden (150 x 200 cm)",
          "1 slaapkamer met stapelbed (75 × 185 cm) – geschikt voor kinderen of jong volwassenen",
          "Videkamer met eenpersoonsbed (90 x 200 cm) + extra breed bed (120 x 200 cm), geschikt voor 1 volwassene of 2 kinderen",
          "Kindvriendelijke speelhoek op de vide met daybed (120 x 175 cm), tv en traphekje",
          "2 badkamers met douche en toilet, één met directe toegang tot de sauna",
          "Gezellige woonkamer met houtkachel, tv en bergzicht",
          "Volledig uitgeruste keuken met kookplaat, oven, magnetron, vaatwasser, koelkast, vriezer, Nespresso-machine met melkopschuimer en waterkoker",
          "Bijkeuken met wasmachine, droger en aparte binnenberging voor bagage en sportuitrusting"
        ],
        "title": "Indeling & faciliteiten"
      }
    },
    "no": {
      "hero": {
        "title": "Koselig ski-inn/ski-ut fjellhytte med badstue",
        "badges": [
          {
            "label": "Sengeplasser",
            "value": "8–9"
          },
          {
            "label": "Høyde",
            "value": "800 m"
          },
          {
            "label": "Badstue",
            "value": "Privat"
          }
        ],
        "subtitle": "Frittliggende hytte i Fageråsen (Trysil) med ski-inn/ski-ut, privat badstue og panoramautsikt over fjellene."
      },
      "meta": {
        "name": "Koselig ski-inn/ski-ut fjellhytte med badstue",
        "sleeps": "8–9",
        "altitude": "800 m",
        "locationShort": "Fageråsen, Trysil, Norge"
      },
      "location": {
        "title": "Beliggenhet",
        "mapQuery": "Fageråsen 701, Trysil",
        "distances": [
          {
            "label": "Transportløype",
            "value": "ca. 50 m"
          },
          {
            "label": "Langrennsløype",
            "value": "ca. 150 m"
          },
          {
            "label": "Skilift (Skistar Høyfjellssenter)",
            "value": "ca. 1,4 km"
          },
          {
            "label": "Skistar Lodge med restauranter, spa, butikker og bar",
            "value": "7 minutters gange eller på ski"
          },
          {
            "label": "Tur- og terrengsykkelstier",
            "value": "i nærheten"
          }
        ]
      },
      "policies": {
        "title": "Vilkår",
        "blocks": [
          {
            "items": [
              "50% av totalbeløpet betales ved reservasjon.",
              "Resterende beløp skal betales 7 dag(er) før ankomst."
            ],
            "title": "Betalingsplan"
          },
          {
            "items": [
              "Alle betalte forskuddsbeløp er ikke-refunderbare."
            ],
            "title": "Avbestillingsregler"
          },
          {
            "items": [
              "Ingen sikkerhetsdepositum kreves."
            ],
            "title": "Sikkerhetsdepositum"
          }
        ]
      },
      "amenities": {
        "title": "Fasiliteter",
        "groups": [
          {
            "items": [
              "Privat tørrbadstue"
            ],
            "title": "Spa"
          },
          {
            "items": [
              "Parkering inkludert",
              "Elbillader ved hytta",
              "Privat hage",
              "Privat lekeplass",
              "Privat veranda"
            ],
            "title": "Parkering og fasiliteter"
          },
          {
            "items": [
              "Barn velkommen",
              "Allergivennlig miljø",
              "Røyking ikke tillatt"
            ],
            "title": "Regler"
          },
          {
            "items": [
              "Kullgrill",
              "Gassgrill",
              "Blender",
              "Barnestol",
              "Kaffemaskin",
              "Kjøkkenutstyr",
              "Oppvaskmaskin",
              "Grill",
              "Kokeplate",
              "Mikrobølgeovn",
              "Ovn",
              "Kjøleskap",
              "Brødrister",
              "Støvsuger"
            ],
            "title": "Kjøkken og spiseplass"
          },
          {
            "items": [
              "Fjell",
              "Resort",
              "Ski inn/ut"
            ],
            "title": "Beliggenhet"
          },
          {
            "items": [
              "Tørketrommel",
              "Basisutstyr",
              "Strykejern og strykebrett",
              "Dusj",
              "Servant",
              "Vaskemaskin"
            ],
            "title": "Bad og vaskerom"
          },
          {
            "items": [
              "Aircondition",
              "Elektrisk oppvarming",
              "Peis",
              "Gulvvarme",
              "Oppvarming tilgjengelig",
              "Ved-/kakkelovn"
            ],
            "title": "Oppvarming og kjøling"
          },
          {
            "items": [
              "Stereoanlegg",
              "TV (antenne)"
            ],
            "title": "Underholdning"
          },
          {
            "items": [
              "Trådløst bredbånd"
            ],
            "title": "Internett og arbeidsplass"
          },
          {
            "items": [
              "Brannslukker",
              "Førstehjelpsutstyr",
              "Røykvarsler"
            ],
            "title": "Sikkerhet"
          }
        ]
      },
      "experience": [
        "Ski inn/ut",
        "Privat badstue",
        "Panoramautsikt",
        "Stier starter ved hytta",
        "Familievennlig loft"
      ],
      "houseRules": {
        "title": "Husregler",
        "bullets": [
          "Barn velkommen",
          "Allergivennlig miljø",
          "Røyking ikke tillatt"
        ],
        "checkIn": "Fra 17:00",
        "checkOut": "Senest 10:00",
        "wifiNote": "Gratis Wi-Fi er tilgjengelig i hele hytta.",
        "checkInNote": "Innsjekk via elektronisk lås med personlig kode.",
        "cleaningNote": "Leie av sengetøy og sluttrengjøring av bad og oppholdsrom er obligatorisk og faktureres separat. Gjestene bes om å etterlate hytta ryddig: fjern søppel og aske fra peisen, sett alle møbler tilbake på plass (inne og ute), og etterlat brukte tallerkener, kjøkkenutstyr, ovn og mikrobølgeovn rene."
      },
      "description": [
        "Frittliggende hytte i Fageråsen (Trysil) med ski-inn/ski-ut, privat badstue og panoramautsikt over fjellene. Sengeplasser 8–9. Overbygd veranda med BBQ og varmer. Koselig stue med vedovn, 2 bad, barnevennlig loft og fullt utstyrt kjøkken. Tur- og terrengsykkelstier starter ved huset. Rolig beliggenhet på 800 moh, 7 minutters gange fra Skistar Lodge. Perfekt for komfort, natur og aktive ferier hele året.",
        "Huset passer svært godt for familier og grupper. Hytta har komfortable sengeplasser til 8 personer, med en ekstra bred seng (120 cm) på loftet. På grunn av skråtaket er denne sengen spesielt egnet for to barn eller én voksen."
      ],
      "accessAndTransport": {
        "car": [
          "Biladkomst fra Oslo via E6/Rv3/Rv25 mot Trysil."
        ],
        "notes": [
          "Vennligst merk at veien til hytta er en bomvei."
        ],
        "title": "Adkomst og transport",
        "parking": [
          "God parkering rett ved hytta",
          "Shuttlebuss går hver 30. minutt om morgenen og ettermiddagen",
          "Lading: Elbillader ved hytta."
        ],
        "airports": [
          "Scandinavian Mountains Airport (Sälen/Trysil): 40 minutter",
          "Oslo lufthavn Gardermoen: 2,5 timer"
        ],
        "publicTransport": [
          "Nor-Way Trysil Express til Skistar Lodge: ca. 3 timer",
          "Fra Oslo S: Trysil Express tog på 3,5 timer",
          "Fjällexpressen fra Malmö, Göteborg og Stockholm i vintersesongen"
        ]
      },
      "layoutAndFacilities": {
        "items": [
          "4 soverom med 5 senger",
          "2 soverom med dobbeltsenger (150 x 200 cm)",
          "1 soverom med køyeseng (75 × 185 cm) – egnet for barn eller unge voksne",
          "Loftsrom med enkeltseng (90 x 200 cm) + ekstra bred seng (120 x 200 cm), egnet for 1 voksen eller 2 barn",
          "Barnevennlig lekehjørne på loftet med daybed (120 x 175 cm), TV og trappegrind",
          "2 bad med dusj og toalett, ett med direkte tilgang til badstuen",
          "Koselig stue med vedovn, TV og fjellutsikt",
          "Fullt utstyrt kjøkken med kokeplate, ovn, mikrobølgeovn, oppvaskmaskin, kjøleskap, fryser, Nespresso-maskin med melkeskummer og vannkoker",
          "Vaskerom med vaskemaskin, tørketrommel og separat innendørs lagring for bagasje og sportsutstyr"
        ],
        "title": "Planløsning og fasiliteter"
      }
    }
  },
  "home": {
    "en": {
      "faq": [
        {
          "answer": "You will receive a digital guide and door code 24 hours before arrival. Self check-in from 17:00.",
          "question": "How does check-in work?"
        },
        {
          "answer": "Pets are not allowed to keep the cabin allergen-friendly.",
          "question": "Are pets allowed?"
        },
        {
          "answer": "Yes, bed linens and towels are included for all guests.",
          "question": "Are linens and towels provided?"
        }
      ],
      "reviews": [
        {
          "name": "James",
          "stay": "Feb 2024",
          "quote": "Perfect location close to the slopes with a calm atmosphere."
        },
        {
          "name": "Nora",
          "stay": "Jan 2024",
          "quote": "Bright, warm, and equipped with everything we needed."
        },
        {
          "name": "Leo",
          "stay": "Dec 2023",
          "quote": "Fast internet and a cozy fireplace after skiing."
        }
      ],
      "tagline": "Comfortable cabin in Trysil, ideal for skiing and summer activities.",
      "keyFacts": [
        {
          "label": "guests",
          "value": "8-9"
        },
        {
          "label": "living area",
          "value": "106 m²"
        },
        {
          "label": "bedrooms",
          "value": "4"
        },
        {
          "label": "bathrooms",
          "value": "2"
        }
      ],
      "location": {
        "description": "Set in Fageråsen with easy access to slopes, lifts, and trails."
      },
      "amenities": [
        "Underfloor heating",
        "Fast internet",
        "Dishwasher",
        "Washing machine",
        "Drying room",
        "Fireplace",
        "Parking at the cabin",
        "EV charger at the cabin"
      ],
      "highlights": [
        {
          "title": "Close to slopes and trails",
          "description": "Ski-in/ski-out access"
        },
        {
          "title": "Family friendly layout",
          "description": "Space for everyone"
        },
        {
          "title": "Panoramic views",
          "description": "Mountain views"
        },
        {
          "title": "Private sauna",
          "description": "Warm up after skiing"
        }
      ],
      "highlightImages": [
        {
          "alt": "Cabin close to the ski slopes in Fageråsen.",
          "src": "/images/highlights/close_to_piste.jpg"
        },
        {
          "alt": "Family-friendly living area with open layout.",
          "src": "/images/highlights/family_friendly_layout.jpg"
        },
        {
          "alt": "Panoramic mountain view.",
          "src": "/images/highlights/panoramic_view.jpg"
        },
        {
          "alt": "Private sauna inside the cabin.",
          "src": "/images/highlights/private_sauna.jpg"
        }
      ]
    },
    "nl": {
      "faq": [
        {
          "answer": "Je ontvangt 24 uur voor aankomst een digitale gids en deurcode. Zelf inchecken vanaf 17:00.",
          "question": "Hoe werkt het inchecken?"
        },
        {
          "answer": "Huisdieren zijn niet toegestaan om het chalet allergievriendelijk te houden.",
          "question": "Zijn huisdieren toegestaan?"
        },
        {
          "answer": "Ja, beddengoed en handdoeken zijn inbegrepen voor alle gasten.",
          "question": "Zijn beddengoed en handdoeken inbegrepen?"
        }
      ],
      "reviews": [
        {
          "name": "Sanne",
          "stay": "Feb 2024",
          "quote": "Fantastische ligging vlak bij de piste en toch rustig."
        },
        {
          "name": "Mark",
          "stay": "Jan 2024",
          "quote": "Licht, warm en alles wat je nodig hebt is aanwezig."
        },
        {
          "name": "Eva",
          "stay": "Dec 2023",
          "quote": "Snel internet en een heerlijke open haard na het skiën."
        }
      ],
      "tagline": "Comfortabel chalet in Trysil, ideaal voor skiën en zomeractiviteiten.",
      "keyFacts": [
        {
          "label": "gasten",
          "value": "8-9"
        },
        {
          "label": "oppervlakte",
          "value": "106 m²"
        },
        {
          "label": "slaapkamers",
          "value": "4"
        },
        {
          "label": "badkamers",
          "value": "2"
        }
      ],
      "location": {
        "description": "In Fageråsen, op loopafstand van pistes, liften en trails."
      },
      "amenities": [
        "Vloerverwarming",
        "Snel internet",
        "Vaatwasser",
        "Wasmachine",
        "Droogruimte",
        "Open haard",
        "Parkeren bij het chalet",
        "Laadpunt bij het chalet"
      ],
      "highlights": [
        {
          "title": "Dicht bij pistes en trails",
          "description": "Ski-in/ski-out ligging"
        },
        {
          "title": "Gezinsvriendelijke indeling",
          "description": "Ruimte voor iedereen"
        },
        {
          "title": "Panoramisch uitzicht",
          "description": "Uitzicht op bergen"
        },
        {
          "title": "Privé sauna",
          "description": "Warm op na skiën"
        }
      ],
      "highlightImages": [
        {
          "alt": "Chalet vlak bij de skipiste in Fageråsen.",
          "src": "/images/highlights/close_to_piste.jpg"
        },
        {
          "alt": "Gezinsvriendelijke woonkamer met open indeling.",
          "src": "/images/highlights/family_friendly_layout.jpg"
        },
        {
          "alt": "Panoramisch uitzicht over de bergen.",
          "src": "/images/highlights/panoramic_view.jpg"
        },
        {
          "alt": "Privé sauna in het chalet.",
          "src": "/images/highlights/private_sauna.jpg"
        }
      ]
    },
    "no": {
      "faq": [
        {
          "answer": "Du får digital guide og dørkode 24 timer før ankomst. Selv-innsjekk fra 17:00.",
          "question": "Hvordan fungerer innsjekk?"
        },
        {
          "answer": "Kjæledyr er ikke tillatt for å holde hytta allergivennlig.",
          "question": "Er kjæledyr tillatt?"
        },
        {
          "answer": "Ja, sengetøy og håndklær er inkludert for alle gjester.",
          "question": "Er sengetøy og håndklær inkludert?"
        }
      ],
      "reviews": [
        {
          "name": "Ingrid",
          "stay": "Feb 2024",
          "quote": "Perfekt beliggenhet nær bakkene og likevel rolig."
        },
        {
          "name": "Erik",
          "stay": "Jan 2024",
          "quote": "Lys, varm og med alt vi trengte."
        },
        {
          "name": "Lina",
          "stay": "Dec 2023",
          "quote": "Raskt internett og en koselig peis etter ski."
        }
      ],
      "tagline": "Komfortabel hytte i Trysil, perfekt for ski og sommeraktiviteter.",
      "keyFacts": [
        {
          "label": "gjester",
          "value": "8-9"
        },
        {
          "label": "boareal",
          "value": "106 m²"
        },
        {
          "label": "soverom",
          "value": "4"
        },
        {
          "label": "bad",
          "value": "2"
        }
      ],
      "location": {
        "description": "I Fageråsen med kort vei til bakker, heiser og løyper."
      },
      "amenities": [
        "Gulvvarme",
        "Raskt internett",
        "Oppvaskmaskin",
        "Vaskemaskin",
        "Tørkerom",
        "Peis",
        "Parkering ved hytta",
        "Elbillader ved hytta"
      ],
      "highlights": [
        {
          "title": "Nær bakker og løyper",
          "description": "Ski-in/ski-out"
        },
        {
          "title": "Familievennlig planløsning",
          "description": "Plass til alle"
        },
        {
          "title": "Panoramautsikt",
          "description": "Utsikt mot fjell"
        },
        {
          "title": "Privat badstue",
          "description": "Varm opp etter ski"
        }
      ],
      "highlightImages": [
        {
          "alt": "Hytta nær skibakken i Fageråsen.",
          "src": "/images/highlights/close_to_piste.jpg"
        },
        {
          "alt": "Familievennlig stue med åpen planløsning.",
          "src": "/images/highlights/family_friendly_layout.jpg"
        },
        {
          "alt": "Panoramautsikt over fjellene.",
          "src": "/images/highlights/panoramic_view.jpg"
        },
        {
          "alt": "Privat badstue i hytta.",
          "src": "/images/highlights/private_sauna.jpg"
        }
      ]
    }
  },
  "practical": {
    "en": {
      "header": {
        "title": "Practical info",
        "subtitle": "Everything you need for a pleasant stay."
      },
      "transport": {
        "title": "Access & transport",
        "columns": [
          {
            "title": "Car",
            "bullets": [
              "Car access from Oslo via E6/Rv3/Rv25 towards Trysil.",
              "Please note: the road to the chalet is a toll road."
            ]
          },
          {
            "title": "Public transport",
            "bullets": [
              "Nor-Way Trysil Express to SkiStar Lodge: approx. 3 hours.",
              "Fjällexpressen from Malmö, Gothenburg and Stockholm during the winter season."
            ]
          },
          {
            "title": "Airports",
            "bullets": [
              "Scandinavian Mountains Airport (Sälen/Trysil): 40 minutes.",
              "Oslo Airport Gardermoen: 2.5 hours."
            ]
          }
        ]
      },
      "goodToKnow": {
        "title": "Good to know",
        "bullets": [
          "Children are very welcome",
          "Low-allergen environment",
          "Smoking is not allowed",
          "Pets are not allowed"
        ]
      },
      "quickFacts": [
        {
          "label": "Check-in",
          "value": "17:00"
        },
        {
          "label": "Check-out",
          "value": "10:00"
        },
        {
          "label": "Guests",
          "value": "8–9"
        },
        {
          "label": "Parking",
          "value": "Private at the chalet"
        },
        {
          "label": "EV charger",
          "value": "Available"
        },
        {
          "label": "Sauna",
          "value": "Private"
        }
      ],
      "contactHelp": {
        "title": "Contact & help",
        "bullets": [
          "Questions or emergencies: contact our local contact person or us.",
          "Contact details are in your booking confirmation."
        ]
      },
      "arrivalAccess": {
        "title": "Arrival & access",
        "bullets": [
          "Self check-in via electronic lock with personal code.",
          "Full privacy during the stay.",
          "Local contact person available in Trysil."
        ],
        "checkIn": "From 17:00",
        "checkOut": "By 10:00",
        "checkInLabel": "Check-in",
        "checkOutLabel": "Check-out"
      },
      "parkingCharging": {
        "title": "Parking & charging",
        "bullets": [
          "Ample parking directly at the chalet.",
          "Shuttle bus runs every 30 minutes in the morning and afternoon.",
          "EV charging: charger at the chalet."
        ],
        "callout": "Please note: the road to the chalet is a toll road."
      },
      "layoutFacilities": {
        "title": "Layout & facilities",
        "sections": [
          {
            "intro": "4 bedrooms with 5 beds, suitable for 8–9 guests",
            "title": "Bedrooms",
            "bullets": [
              "2 bedrooms with double beds (150 × 200 cm)",
              "1 bedroom with bunk bed (75 × 185 cm) – suitable for children or young adults",
              "Attic room with single bed (90 × 200 cm) + extra-wide bed (120 × 200 cm), suitable for 1 adult or 2 children",
              "Due to the sloped roof, the extra-wide bed is especially ideal for children"
            ]
          },
          {
            "title": "Family-friendly loft",
            "bullets": [
              "Play corner on the loft",
              "Daybed (120 × 175 cm)",
              "TV",
              "Stair gate available"
            ]
          },
          {
            "title": "Bathrooms & wellness",
            "bullets": [
              "2 bathrooms with shower and toilet",
              "1 bathroom with direct access to the private sauna"
            ]
          },
          {
            "title": "Living area",
            "bullets": [
              "Cozy living room with wood-burning stove, heat pump, smart TV and mountain views"
            ]
          },
          {
            "intro": "Fully equipped for cooking and dining together",
            "title": "Kitchen",
            "bullets": [
              "Hob and oven",
              "Microwave",
              "Dishwasher",
              "Refrigerator and freezer",
              "Nespresso machine with milk frother",
              "Kettle"
            ]
          },
          {
            "title": "Laundry & storage",
            "bullets": [
              "Washer and dryer",
              "Separate indoor storage for luggage and sports equipment"
            ]
          }
        ]
      },
      "agreementsAndPayment": {
        "title": "Agreements & payment",
        "blocks": [
          {
            "items": [
              "50% at reservation",
              "Remaining balance 7 days before arrival"
            ],
            "title": "Payment"
          },
          {
            "items": [
              "Prepayments are non-refundable"
            ],
            "title": "Cancellation"
          },
          {
            "items": [
              "Linen rental and final cleaning of bathrooms and living areas are mandatory and charged separately"
            ],
            "title": "Linen & cleaning"
          }
        ]
      }
    },
    "nl": {
      "header": {
        "title": "Praktische info",
        "subtitle": "Alles wat je moet weten voor een prettig verblijf."
      },
      "transport": {
        "title": "Bereikbaarheid & vervoer",
        "columns": [
          {
            "title": "Auto",
            "bullets": [
              "Met de auto vanuit Oslo via E6/Rv3/Rv25 richting Trysil.",
              "Let op: de weg naar het chalet is een tolweg."
            ]
          },
          {
            "title": "Openbaar vervoer",
            "bullets": [
              "Nor-Way Trysil Express naar SkiStar Lodge: ca. 3 uur.",
              "Fjällexpressen vanuit Malmö, Göteborg en Stockholm in het winterseizoen."
            ]
          },
          {
            "title": "Luchthavens",
            "bullets": [
              "Scandinavian Mountains Airport (Sälen/Trysil): 40 minuten.",
              "Oslo Airport Gardermoen: 2,5 uur."
            ]
          }
        ]
      },
      "goodToKnow": {
        "title": "Goed om te weten",
        "bullets": [
          "Kinderen zijn van harte welkom",
          "Allergiearme omgeving",
          "Roken is niet toegestaan",
          "Huisdieren zijn niet toegestaan"
        ]
      },
      "quickFacts": [
        {
          "label": "Check-in",
          "value": "17:00"
        },
        {
          "label": "Check-out",
          "value": "10:00"
        },
        {
          "label": "Gasten",
          "value": "8–9"
        },
        {
          "label": "Parkeren",
          "value": "Privé bij het chalet"
        },
        {
          "label": "Oplaadpunt",
          "value": "Aanwezig"
        },
        {
          "label": "Sauna",
          "value": "Privé"
        }
      ],
      "contactHelp": {
        "title": "Contact & hulp",
        "bullets": [
          "Vragen of noodgeval: neem contact op met onze lokale contactpersoon of met ons.",
          "Contactgegevens vind je in je boekingsbevestiging."
        ]
      },
      "arrivalAccess": {
        "title": "Aankomst & toegang",
        "bullets": [
          "Self check-in via elektronisch slot met persoonlijke code.",
          "Volledige privacy tijdens het verblijf."
        ],
        "checkIn": "Vanaf 17:00",
        "checkOut": "Voor 10:00",
        "checkInLabel": "Check-in",
        "checkOutLabel": "Check-out"
      },
      "parkingCharging": {
        "title": "Parkeren & laden",
        "bullets": [
          "Ruime parkeergelegenheid direct bij het chalet.",
          "Shuttlebus rijdt elke 30 minuten in de ochtend en middag.",
          "Oplaadpunt: laadpunt bij het chalet."
        ],
        "callout": "Let op: de weg naar het chalet is een tolweg."
      },
      "layoutFacilities": {
        "title": "Indeling & faciliteiten",
        "sections": [
          {
            "intro": "4 slaapkamers, met 5 bedden, geschikt voor 8–9 gasten",
            "title": "Slaapkamers",
            "bullets": [
              "2 slaapkamers met tweepersoonsbedden (150 × 200 cm)",
              "1 slaapkamer met stapelbed (75 × 185 cm) – geschikt voor kinderen of jong volwassenen",
              "Videkamer met eenpersoonsbed (90 × 200 cm) + extra breed bed (120 × 200 cm), geschikt voor 1 volwassene of 2 kinderen",
              "Door het schuine dak is het extra brede bed vooral ideaal voor kinderen"
            ]
          },
          {
            "title": "Kindvriendelijke vide",
            "bullets": [
              "Speelhoek op de vide",
              "Daybed (120 × 175 cm)",
              "TV",
              "Traphekje aanwezig"
            ]
          },
          {
            "title": "Badkamers & wellness",
            "bullets": [
              "2 badkamers met douche en toilet",
              "1 badkamer met directe toegang tot de privé sauna"
            ]
          },
          {
            "title": "Woonruimte",
            "bullets": [
              "Gezellige woonkamer met houtkachel, warmtepomp, smart TV en bergzicht"
            ]
          },
          {
            "intro": "Volledig uitgerust voor koken en samen eten",
            "title": "Keuken",
            "bullets": [
              "Kookplaat en oven",
              "Magnetron",
              "Vaatwasser",
              "Koelkast en vriezer",
              "Nespresso-machine met melkopschuimer",
              "Waterkoker"
            ]
          },
          {
            "title": "Bijkeuken & opslag",
            "bullets": [
              "Wasmachine en droger",
              "Aparte binnenberging voor bagage en sportuitrusting"
            ]
          }
        ]
      },
      "agreementsAndPayment": {
        "title": "Afspraken & betaling",
        "blocks": [
          {
            "items": [
              "50% bij reservering",
              "Restant 7 dagen voor aankomst"
            ],
            "title": "Betaling"
          },
          {
            "items": [
              "Vooruitbetalingen zijn niet restitueerbaar"
            ],
            "title": "Annulering"
          },
          {
            "items": [
              "Linnenverhuur en eindschoonmaak van badkamers en woonruimtes zijn verplicht en worden apart in rekening gebracht"
            ],
            "title": "Linnen & schoonmaak"
          }
        ]
      }
    },
    "no": {
      "header": {
        "title": "Praktisk info",
        "subtitle": "Alt du trenger for et hyggelig opphold."
      },
      "transport": {
        "title": "Adkomst og transport",
        "columns": [
          {
            "title": "Bil",
            "bullets": [
              "Biladkomst fra Oslo via E6/Rv3/Rv25 mot Trysil.",
              "Merk: veien til hytta er en bomvei."
            ]
          },
          {
            "title": "Offentlig transport",
            "bullets": [
              "Nor-Way Trysil Express til SkiStar Lodge: ca. 3 timer.",
              "Fjällexpressen fra Malmö, Göteborg og Stockholm i vintersesongen."
            ]
          },
          {
            "title": "Flyplasser",
            "bullets": [
              "Scandinavian Mountains Airport (Sälen/Trysil): 40 minutter.",
              "Oslo lufthavn Gardermoen: 2,5 timer."
            ]
          }
        ]
      },
      "goodToKnow": {
        "title": "Godt å vite",
        "bullets": [
          "Barn er hjertelig velkommen",
          "Allergivennlig miljø",
          "Røyking er ikke tillatt",
          "Kjæledyr er ikke tillatt"
        ]
      },
      "quickFacts": [
        {
          "label": "Innsjekk",
          "value": "17:00"
        },
        {
          "label": "Utsjekk",
          "value": "10:00"
        },
        {
          "label": "Gjester",
          "value": "8–9"
        },
        {
          "label": "Parkering",
          "value": "Privat ved hytta"
        },
        {
          "label": "Elbillader",
          "value": "Tilgjengelig"
        },
        {
          "label": "Badstue",
          "value": "Privat"
        }
      ],
      "contactHelp": {
        "title": "Kontakt og hjelp",
        "bullets": [
          "Spørsmål eller nødstilfelle: kontakt vår lokale kontaktperson eller oss.",
          "Kontaktinformasjon finner du i bestillingsbekreftelsen."
        ]
      },
      "arrivalAccess": {
        "title": "Ankomst og tilgang",
        "bullets": [
          "Selvbetjent innsjekk via elektronisk lås med personlig kode.",
          "Fullt privat under oppholdet.",
          "Lokal kontaktperson tilgjengelig i Trysil."
        ],
        "checkIn": "Fra 17:00",
        "checkOut": "Senest 10:00",
        "checkInLabel": "Innsjekk",
        "checkOutLabel": "Utsjekk"
      },
      "parkingCharging": {
        "title": "Parkering og lading",
        "bullets": [
          "God parkering rett ved hytta.",
          "Shuttlebuss går hver 30. minutt om morgenen og ettermiddagen.",
          "Lading: Elbillader ved hytta."
        ],
        "callout": "Merk: veien til hytta er en bomvei."
      },
      "layoutFacilities": {
        "title": "Planløsning og fasiliteter",
        "sections": [
          {
            "intro": "4 soverom med 5 senger, egnet for 8–9 gjester",
            "title": "Soverom",
            "bullets": [
              "2 soverom med dobbeltsenger (150 × 200 cm)",
              "1 soverom med køyeseng (75 × 185 cm) – egnet for barn eller unge voksne",
              "Loftsrom med enkeltseng (90 × 200 cm) + ekstra bred seng (120 × 200 cm), egnet for 1 voksen eller 2 barn",
              "På grunn av skråtaket er den ekstra brede sengen spesielt egnet for barn"
            ]
          },
          {
            "title": "Familievennlig loft",
            "bullets": [
              "Lekeområde på loftet",
              "Daybed (120 × 175 cm)",
              "TV",
              "Trappegrind tilgjengelig"
            ]
          },
          {
            "title": "Bad og velvære",
            "bullets": [
              "2 bad med dusj og toalett",
              "1 bad med direkte tilgang til privat badstue"
            ]
          },
          {
            "title": "Oppholdsrom",
            "bullets": [
              "Koselig stue med vedovn, varmepumpe, smart TV og fjellutsikt"
            ]
          },
          {
            "intro": "Fullt utstyrt for matlaging og felles måltider",
            "title": "Kjøkken",
            "bullets": [
              "Kokeplate og ovn",
              "Mikrobølgeovn",
              "Oppvaskmaskin",
              "Kjøleskap og fryser",
              "Nespresso-maskin med melkeskummer",
              "Vannkoker"
            ]
          },
          {
            "title": "Vaskerom og lagring",
            "bullets": [
              "Vaskemaskin og tørketrommel",
              "Separat innendørs lagring for bagasje og sportsutstyr"
            ]
          }
        ]
      },
      "agreementsAndPayment": {
        "title": "Avtaler og betaling",
        "blocks": [
          {
            "items": [
              "50% ved reservasjon",
              "Restbeløpet 7 dager før ankomst"
            ],
            "title": "Betaling"
          },
          {
            "items": [
              "Forhåndsbetalinger refunderes ikke"
            ],
            "title": "Avbestilling"
          },
          {
            "items": [
              "Leie av sengetøy og sluttrengjøring av bad og oppholdsrom er obligatorisk og faktureres separat"
            ],
            "title": "Sengetøy og renhold"
          }
        ]
      }
    }
  },
  "area": {
    "en": {
      "intro": "Trysil is a year-round destination for outdoor lovers.",
      "sections": [
        {
          "title": "Winter",
          "bullets": [
            "Ski-in/ski-out access to Trysilfjellet",
            "Extensive cross-country trail network",
            "Ski rental and school nearby"
          ],
          "description": "Skiing, cross-country trails, and cozy evenings."
        },
        {
          "title": "Summer",
          "bullets": [
            "Marked hiking routes around Fageråsen",
            "Mountain bike trails and lift access",
            "Swimming spots and river activities"
          ],
          "description": "Hiking, biking, and crisp mountain air."
        }
      ]
    },
    "nl": {
      "intro": "Trysil is het hele jaar door een actieve bestemming.",
      "sections": [
        {
          "title": "Winter",
          "bullets": [
            "Ski-in/ski-out naar Trysilfjellet",
            "Uitgebreid netwerk van langlaufloipes",
            "Skiverhuur en skischool dichtbij"
          ],
          "description": "Skiën, langlauf en sfeervolle avonden."
        },
        {
          "title": "Zomer",
          "bullets": [
            "Gemarkeerde wandelroutes rond Fageråsen",
            "Mountainbike trails en lift",
            "Zwemplekken en rivieractiviteiten"
          ],
          "description": "Wandelen, fietsen en frisse berglucht."
        }
      ]
    },
    "no": {
      "intro": "Trysil er et helårs reisemål for friluftsliv.",
      "sections": [
        {
          "title": "Vinter",
          "bullets": [
            "Ski-in/ski-out til Trysilfjellet",
            "Stort nettverk av langrennsløyper",
            "Skileie og skiskole i nærheten"
          ],
          "description": "Ski, langrenn og koselige kvelder."
        },
        {
          "title": "Sommer",
          "bullets": [
            "Merkede turstier rundt Fageråsen",
            "Stisykkel og heis",
            "Badeplasser og elveaktiviteter"
          ],
          "description": "Vandring, sykling og frisk fjelluft."
        }
      ]
    }
  },
  "privacy": {
    "en": {
      "intro": "We respect your privacy and only process data needed for your inquiry or booking.",
      "bullets": [
        "We use your data only to respond and manage your stay.",
        "Bookings are handled through Lodgify and their privacy policy applies.",
        "You can request deletion of your data at any time."
      ]
    },
    "nl": {
      "intro": "We respecteren je privacy en verwerken alleen de gegevens die nodig zijn voor je aanvraag of boeking.",
      "bullets": [
        "We gebruiken je gegevens uitsluitend om contact op te nemen en je verblijf te regelen.",
        "Boekingen worden afgehandeld via Lodgify en hun privacybeleid is van toepassing.",
        "Je kunt ons vragen je gegevens te verwijderen."
      ]
    },
    "no": {
      "intro": "Vi respekterer personvernet ditt og behandler kun data som trengs for forespørsel eller bestilling.",
      "bullets": [
        "Vi bruker dataene dine kun for å svare og administrere oppholdet.",
        "Bestillinger håndteres via Lodgify og deres personvern gjelder.",
        "Du kan be om sletting av dataene dine når som helst."
      ]
    }
  },
  "contactForm": {
    "en": {
      "form": {
        "name": {
          "label": "Name",
          "placeholder": "Your full name"
        },
        "email": {
          "label": "Email",
          "placeholder": "you@email.com"
        },
        "error": "Something went wrong while sending. Please try again later.",
        "period": {
          "label": "Preferred period",
          "placeholder": "For example 12–19 February (optional)"
        },
        "submit": "Send message",
        "message": {
          "label": "Message",
          "placeholder": "Your question or message"
        },
        "success": "Thank you! Your message has been sent. We will get back to you as soon as possible."
      },
      "title": "Contact & availability",
      "subtitle": "Have questions about availability, the area, or the stay in Fageråsen in Trysil? Use the contact form below or reach out directly via email: info@trysilpanorama.com."
    },
    "nl": {
      "form": {
        "name": {
          "label": "Naam",
          "placeholder": "Je volledige naam"
        },
        "email": {
          "label": "E-mail",
          "placeholder": "je@emailadres.nl"
        },
        "error": "Er ging iets mis bij het verzenden. Probeer het later opnieuw.",
        "period": {
          "label": "Gewenste periode",
          "placeholder": "Bijvoorbeeld 12–19 februari (optioneel)"
        },
        "submit": "Stuur bericht",
        "message": {
          "label": "Bericht",
          "placeholder": "Je vraag of bericht"
        },
        "success": "Dank je wel! Je bericht is verzonden. We nemen zo snel mogelijk contact met je op."
      },
      "title": "Contact & beschikbaarheid",
      "subtitle": "Heb je vragen over beschikbaarheid, de omgeving of het verblijf in Fageråsen in Trysil? Gebruik het contactformulier hieronder of neem direct contact met ons op via e-mail: info@trysilpanorama.com."
    },
    "no": {
      "form": {
        "name": {
          "label": "Navn",
          "placeholder": "Ditt fulle navn"
        },
        "email": {
          "label": "E-post",
          "placeholder": "du@epost.no"
        },
        "error": "Noe gikk galt under sendingen. Prøv igjen senere.",
        "period": {
          "label": "Ønsket periode",
          "placeholder": "For eksempel 12.–19. februar (valgfritt)"
        },
        "submit": "Send melding",
        "message": {
          "label": "Melding",
          "placeholder": "Spørsmålet ditt eller melding"
        },
        "success": "Takk! Meldingen din er sendt. Vi tar kontakt så snart som mulig."
      },
      "title": "Kontakt og tilgjengelighet",
      "subtitle": "Har du spørsmål om tilgjengelighet, området eller oppholdet i Fageråsen i Trysil? Bruk kontaktskjemaet nedenfor eller ta direkte kontakt med oss på e-post: info@trysilpanorama.com."
    }
  }
};
